#!/bin/bash

brew install wget
brew install gnupg2
brew install git

brew install maven
brew cask install java

brew cask install slack
brew cask install virtualbox
brew cask install google-chrome
brew cask install iterm2

